/////////////////////////////////////////////////////////////////////////////////////////////////////
// Unit tests using the doctest framework.
//
// This file serves as a placeholder for main(), which is generated by doctest.
//
// See the documentation section for an overview: https://github.com/onqtam/doctest#documentation
//
// Running with filtering of flags:
//
//    > sudo ./obj/qpu-debug/bin/runTests -tc=*[ops]*,*[dft]*    // all tests matching at least one tag
//    > sudo ./obj/qpu-debug/bin/runTests -tce=*[matrix]*        // Exclude all tags in list
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
#include "Support/debug.h"
#include "global/log.h"     // set_level()

//#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#define DOCTEST_CONFIG_IMPLEMENT
#include "doctest.h"


int main(int argc, char** argv) {
  Log::set_log_dir("log");
  Log::set_log_file("unit_tests.log");

  doctest::Context context;
  context.applyCommandLine(argc, argv);
  int res = context.run();              // run
  if(context.shouldExit()) {            // important - query flags (and --exit) rely on the user doing this
    return res;                         // propagate the result of the tests
  }
   
  return 0;
}
