NAME=Rot3D

SRCDIR=./


STL_DIR=../../obj/stl

INCLUDE_EXTERN= \
 -I ../../extern/stl/src

LIB_EXTERN= \
 -L $(STL_DIR)/bin -lstl

-include /home/wim/projects/V3DLib/script/mak/config.mak
-include /home/wim/projects/V3DLib/script/mak/subproject.mak

